version: "3"
services:

  master:
    build: ./master
    command: ["/usr/bin/supervisord"]
    ports:
      - "4505:4505"
      - "4506:4506"
  slave:
    build: ./slave
    command: ["salt-minion", "-l", "debug"]
    external_links:
      - master:salt